### ISSUE TITLE
Which user-rights?

### ISSUE THREAD

**Issue by dan-m-joh** [SNapier/Check_VCSA_Mon#1]
Hello,

This plugin looks great (have not yet bin able to test it....)

I have a question regarding the needed user-rights: Which rights does the user need to have be able to use this plugin?
Our VMware admins do not want to grant "everybody" "everything", instead they just want to grant the necessary rights.

Regards,
Dan

**Comment by SNapier** [comment]
Dan,
In testing I created a dedicated role for the interaction between the library and the API.

(AS SuperAdmin via Appliance Shell ) 
1. I cloned the "Operator" role to "Monitoring"
2. Created new local user with "Monitoring" role 
3. I gave full RO access to the API get commands

Trust but verify 
1. I tested the login and session ID generation via the REST API Explorer.
2. I then tested the API "GET" data collection via the REST API Explorer.

Appliance Shell Docs
[https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcsa.doc/GUID-F972C583-1423-4A14-AECB-0A588F918DFB.html(https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcsa.doc/GUID-F972C583-1423-4A14-AECB-0A588F918DFB.html)

Permissions For Each Command Explained
[https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcsa.doc/GUID-ACEC0944-EFA7-482B-84DF-6A084C0868B3.html)(https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcsa.doc/GUID-ACEC0944-EFA7-482B-84DF-6A084C0868B3.html)
